packages:
  - "."
  - "mcp"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
overrides:
  vite: "catalog:"
allowBuilds:
  core-js-pure: set this to true or false
  esbuild: true
  workerd: true
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
