/**
 * Generates the artifacts that tie Tailwind and TypeScript to themes.
 *
 * Two things have to agree with the `#theme` import alias, and both are
 * invisible when they do not: which theme's tokens are loaded, and which
 * directory Tailwind scans for utilities. Point either at the wrong theme and
 * the build still succeeds — it just ships the wrong palette, or no utilities
 * at all.
 *
 * DESIGN RULE: every write here is a deterministic function of the theme list on
 * disk plus theme.config.json. The THEME environment variable never
 * changes a single generated byte. This is what makes concurrent processes
 * safe: a `THEME=studio astro build` running beside a default dev server
 * writes exactly the bytes the dev server would write, the idempotent-write
 * skip turns that into no write at all, and no watcher fires. (Before this
 * rule, that exact scenario shipped a corrupt worker: the dev server noticed
 * the shared tsconfig change, restarted, wrote both shared files back to its
 * own theme, and the build's Tailwind then read the reverted stylesheet — it
 * exited 0 carrying studio templates with default styling.)
 *
 * Per-process selection happens in process-local state only:
 *   - the `#theme` and `#theme-css` Vite aliases (astro.config.mjs,
 *     vitest.config.ts)
 *   - an explicit `astro check --tsconfig tsconfig.theme.<id>.json`
 *
 * The files are generated, not committed.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { CONFIG_FILE, THEMES_DIR, discoverThemeIds, resolveConfiguredTheme } from "./themes.mjs";

/** One stylesheet per theme, so selecting a theme is an alias, not a rewrite. */
export const GENERATED_CSS_DIR = "src/styles/themes";
/** The editor-facing tsconfig fragment; follows theme.config.json only. */
export const SHARED_TSCONFIG = "tsconfig.theme.json";

export function themeCssPath(id, root = process.cwd()) {
  return resolve(root, GENERATED_CSS_DIR, `${id}.css`);
}

export function themeTsconfigPath(id, root = process.cwd()) {
  return resolve(root, `tsconfig.theme.${id}.json`);
}

export function themeCss(id, root = process.cwd()) {
  // Relative to GENERATED_CSS_DIR (src/styles/themes/).
  const toThemes = "../../themes";
  // Exclude each INACTIVE theme individually. Excluding the parent and then
  // re-including the active child does not work: the exclusion wins, and the
  // active theme's utilities silently vanish along with the others'. Verified by
  // building a probe theme and finding its unique utility absent even when the
  // probe was selected.
  const inactive = discoverThemeIds(root).filter((other) => other !== id);
  const exclusions = inactive.length
    ? inactive.map((other) => `@source not "${toThemes}/${other}";`).join("\n")
    : "/* no inactive themes */";

  return `/*
 * GENERATED — do not edit, and do not commit.
 * Written by scripts/theme-css.mjs. One of these exists per theme; the
 * #theme-css alias picks which one a given process compiles.
 * This file selects: ${id}
 */

/* Tailwind auto-detects sources, so every sibling theme would otherwise
   contribute utilities no page can use. Inactive themes are excluded one by one;
   the active theme is left to normal detection. */
${exclusions}

/* The active theme's design tokens. src/styles/overrides.css is imported after
   this by global.css, so a merchant's overrides still win. */
@import "${toThemes}/${id}/tokens.css";
`;
}

function themeTsconfig(id) {
  return `${JSON.stringify(
    {
      $comment: `GENERATED by scripts/theme-css.mjs — selects theme: ${id}. Do not edit or commit. Consumed via astro check --tsconfig.`,
      extends: "./tsconfig.json",
      compilerOptions: { paths: { "#theme/*": [`./${THEMES_DIR}/${id}/*`] } },
    },
    null,
    2,
  )}\n`;
}

function sharedTsconfig(id) {
  return `${JSON.stringify(
    {
      $comment: `GENERATED by scripts/theme-css.mjs from ${CONFIG_FILE} — theme: ${id}. Do not edit or commit.`,
      compilerOptions: { paths: { "#theme/*": [`./${THEMES_DIR}/${id}/*`] } },
    },
    null,
    2,
  )}\n`;
}

/** Idempotent: only rewrites when the content changes, so a watching dev
 *  server never sees a modification event for identical bytes. */
function writeIfChanged(file, next) {
  try {
    if (readFileSync(file, "utf8") === next) return file;
  } catch {
    // Not written yet.
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, next);
  return file;
}

/**
 * Write everything: one CSS file and one tsconfig per discovered theme, plus the
 * shared editor tsconfig from the config file. Artifacts for themes that no
 * longer exist are removed, so a deleted theme does not leave a pair pointing at
 * a missing directory. Called by astro.config.mjs (so a bare `astro dev` on a
 * fresh clone works) and by `npm run theme:sync`.
 */
export function writeThemeArtifacts(root = process.cwd()) {
  const ids = discoverThemeIds(root);
  for (const id of ids) {
    writeIfChanged(themeCssPath(id, root), themeCss(id, root));
    writeIfChanged(themeTsconfigPath(id, root), themeTsconfig(id));
  }

  // The Admin entry's exclusion list: EVERY theme, because no theme's templates
  // render inside Admin and no theme may restyle it. Named with a leading
  // underscore, which no theme id can carry, so it cannot collide with a theme's
  // own generated file.
  const adminExclusions = ids.map((id) => `@source not "../../themes/${id}";`).join("\n");
  writeIfChanged(
    resolve(root, GENERATED_CSS_DIR, "_admin.css"),
    `/*
 * GENERATED — do not edit, and do not commit.
 * Written by scripts/theme-css.mjs for src/styles/admin.css: keeps every
 * themes out of the Admin stylesheet's source scan.
 */
${adminExclusions || "/* no themes */"}
`,
  );

  const live = new Set(ids);
  const cssDir = resolve(root, GENERATED_CSS_DIR);
  if (existsSync(cssDir)) {
    for (const name of readdirSync(cssDir)) {
      if (name.startsWith("_")) continue; // not per-theme (e.g. _admin.css)
      const id = name.replace(/\.css$/, "");
      if (name.endsWith(".css") && !live.has(id)) rmSync(resolve(cssDir, name), { force: true });
    }
  }
  for (const name of readdirSync(root)) {
    const m = name.match(/^tsconfig\.theme\.([a-z0-9-]+)\.json$/);
    if (m && !live.has(m[1])) rmSync(resolve(root, name), { force: true });
  }

  // The one shared file. It exists for the editor and for a bare `astro
  // check`, and it deliberately ignores THEME — see the design rule
  // above. Env-selected processes pass their per-theme tsconfig explicitly.
  const configured = resolveConfiguredTheme(root);
  writeIfChanged(resolve(root, SHARED_TSCONFIG), sharedTsconfig(configured.id));

  return { ids, configured };
}
