import type { APIRoute } from "astro";
import { env } from "cloudflare:workers";
import { verifyDeployPurgeAuthorization } from "../../../features/cache/deployPurgeAuth";
import { purgeEntireCache } from "../../../features/cache/purge";

export const prerender = false;

const json = (body: object, status: number): Response =>
  Response.json(body, {
    status,
    headers: { "cache-control": "private, no-store" },
  });

/**
 * Deployment-only invalidation for cross-version Workers Caching.
 *
 * CACHE_PURGE_SECRET signs a short-lived, single-purpose HMAC generated by
 * scripts/deploy/deploy.mjs. AUTH_SECRET remains a compatibility fallback so existing
 * deployments can opt in without adding a third secret. This route deliberately
 * lives outside /api/admin because Cloudflare Access can intercept that
 * namespace before the Worker runs.
 */
export const POST: APIRoute = async ({ request }) => {
  const secret = env.CACHE_PURGE_SECRET || env.AUTH_SECRET;
  if (!secret) return json({ error: "Deploy purge is not configured." }, 503);

  const authorized = await verifyDeployPurgeAuthorization(
    request.headers.get("authorization"),
    secret,
    Date.now() / 1000,
  );
  if (!authorized) return json({ error: "Unauthorized." }, 401);

  try {
    await purgeEntireCache();
    return json({ success: true }, 200);
  } catch {
    return json({ error: "Cache purge failed." }, 503);
  }
};
